<table border="0">
    <tr>
        <td style="vertical-align: top;">
            <div id="panelbusqueda" align="center" class="ui-widget ui-widget-content ui-corner-all " style="width: 470px;">
                <div class="ui-widget ui-state-default ui-corner-top ui-title">
                    <label>Datos del Documento</label>
                    <input type="hidden" id="Dddocumento" value="<?php echo $this->ddocumento; ?>" />
                    <input type="hidden" id="Dcidsigma" value="<?php echo $this->cidsigma; ?>" />
                    <input type="hidden" id="Dctipjerar" value="<?php echo $this->ctipjerar; ?>" />
                    <input type="hidden" id="Dccate" value="<?php echo $this->ccate; ?>" />
                </div>
                <table border="0" width="460px">
                    <tr>
                        <td><b>NºExpediente</b></td>
                        <td align="left"><input type="text" id="txtnroexpe" class="ui-text" style="text-align: left; width: 120px;" readOnly="true" disabled />
                        </td>
                        <td><b>Fec. Ingreso</b></td>
                        <td align="left"><input type="text" id="txtfecingreso" class="ui-text" style="text-align: left; width: 80px;" readOnly="true" disabled />
                        </td>
                    </tr>
                    <tr>
                        <td><b>Folios</b></td>
                        <td align="left" colspan="4"><input type="text" id="txtfolios" class="ui-text" style="text-align: left; width: 30px;" readOnly="true" disabled />
                        </td>
                    </tr>
                    <tr>
                        <td><b>Administrado</b></td>
                        <td align="left" colspan="4"><input type="text" id="txtrecurrente" class="ui-text" style="text-align: left; width: 95%;" readOnly="true" disabled />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            <hr />
                        </td>
                    </tr>
                    <tr>
                        <td><b>Tipo</b></td>
                        <td align="left" colspan="4"><select id="cbotipodoc" style="text-align: left; width: 205px;"></select>
                        </td>
                    </tr>
                    <tr>
                        <td><b>Nro Doc</b></td>
                        <td>

                            <input type="text" id="txtnrodoc" class="ui-text" style="text-align: left; width: 180px;" <?php echo ($this->ccate == '1' ? 'disabled' : ''); ?> />

                            <input type="checkbox" id="chknrodoc" <?php echo ($this->ccate == '2' ? 'style="display: none;"' : 'checked'); ?> />

                        </td>
                        <td><b>Fec. Ingreso</b></td>
                        <td align="left"><input type="text" id="txtfecingresodoc" class="ui-text" style="text-align: left; width: 80px;" />
                        </td>
                    </tr>

                    <tr>

                        <td><b>Relevancia</b></td>
                        <td align="left" colspan="4"><select id="cborelevancia" style="text-align: left; width: 205px;"></select>
                        </td>
                    </tr>
                    <!--MODIFICADO 0106-->
                    <tr>
                        <td><b>Folios</b></td>
                        <td style="text-align: left">
                            <input class="editable ui-text" size="19" type="text" id="txtvfolios" name="txtvfolios" value="<?php echo $this->vfolios; ?>" />
                        </td>
                    </tr>
                    <tr>
                        <td align="center" colspan="4"><b>Obvervaciones</b></td>
                    </tr>
                    <tr>
                        <td colspan="4"><textarea id="txtobservacion">
                                <?php echo $this->observ; ?>
                            </textarea>
                        </td>
                    </tr>
                </table>
            </div>
        </td>
        <td style="vertical-align: top;">
            <div id="tabs_ddocument" style="width: 470px;">
                <ul>

                    <li><a href="#tabs-1">Datos del Documento</a></li>
                    <li><a href="#tab-adjuntos">Adjuntos</a></li>
                    <li><a href="#tabs-2">Subir Adjuntos</a></li>

                </ul>
                <div id="tabs-1">
                    <div id="paneltblResultDocdetalle">
                        <table id="tblResultDocdetalle"></table>
                        <div id="ptblResultDocdetalle"></div>
                        <input type="hidden" id="ctblResultDocdetalle" name="ctblResultDocdetalle" value="" />
                    </div>
                </div>
                <div id="tab-adjuntos">
                    <div id="DpanelResultDocAdjunto">
                        <table id="DtblResultDocAdjunto">
                        </table>
                        <div id="pDtblResultDocAdjunto"></div>
                        <input type="hidden" id="cDtblResultDocAdjunto" name="cDtblResultDocAdjunto" value="" />
                    </div>
                </div>
                <div id="tabs-2">
                    <table style="width: 440px;" border="0">
                        <tr style="display: none;">
                            <td><b>Tipo de Adjunto</b></td>
                            <td style="width: 70%;"><select id="cbotipadjunto" style="width: 150px;">
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <div id="dv_ie8" style="display:none;">
                                    <!--    <button id="btnplusfile">Pluss</button><br/>  -->
                                    <iframe src="<?php echo $this->util()->getPath(); ?>index.php/documentos/iframedocumentupload" width="100%" height="40px" frameborder="0">

                                    </iframe>
                                </div>
                                <div id="browserX" style="display:none;">
                                    <div id="manual-fine-uploader"></div>
                                    <button id="btnsuubirarchivos" style="margin-top: 10px;">Subir Archivos</button>
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </td>
    </tr>
</table>
<div id="dialogOBS">
</div>
<script>
    var manualuploader;
    $(document).ready(function() {

        $("#tabs_ddocument").tabs();
        $('#tabs_ddocument').tabs('select', 0);

        var config = {
            skin: 'v2',
            toolbar: [
                ['Bold', 'Italic', 'Underline', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Undo', 'Redo', '-', 'HorizontalRule', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'TextColor', 'BGColor'],
                ['UIColor']
            ]
            //,readOnly: true
        };

        var hEd = CKEDITOR.instances['txtobservacion'];
        if (hEd) {
            CKEDITOR.remove(hEd);
        }
        CKEDITOR.replace('txtobservacion', config);

        manualuploader = new qq.FineUploader({
            debug: false,
            element: document.getElementById('manual-fine-uploader'),
            request: {
                //endpoint: 'uploadddocuments'
                endpoint: path + "documentos/uploadddocuments"
            },
            //template: "qq-template-manual-noedit",
            autoUpload: false
        });

        if (navigator.appName == 'Microsoft Internet Explorer') {
            var ver = getInternetExplorerVersion();
            if (ver > -1) {
                // alert(ver);
                if (ver <= 9.0) {
                    if ("<?php echo $this->ddocumento; ?>" == "") {
                        //$("#tabs-2").hide();
                        $("#tabs").tabs("option", "disabled", [2]);
                    }
                    $("#dv_ie8").show();

                    /* $("#btnplusfile").button({
                        icons: {
                            primary: "ui-icon-plus"
                        },
                        text: false
                    }).click(function() {
                        $("#dv_ie8").append('<iframe src="' + path + 'documentos/iframedocumentupload" width="100%" height="40px" frameborder="0"></iframe>');
                    });
               */

                }
            } else {
                $("#browserX").show();
            }
        } else {
            $("#browserX").show();
        }

        $("#btnsuubirarchivos").button().click(function() {
            if ($("#Dddocumento").val() != "") {
                manualuploader.uploadStoredFiles();
                // manualuploader.fineUploader('uploadStoredFiles');
            }
        });

        $("#txtfecingresodoc").datepicker({
            showOn: "button",
            buttonImage: jQuery.scriptPath + "img/calendar.gif",
            buttonImageOnly: true,
            dateFormat: "dd/mm/yy"
        });
        $('#chknrodoc').change(function() {
            if ($(this).is(':checked')) {
                $("#txtnrodoc").attr("disabled", "disabled");
            } else {
                $("#txtnrodoc").removeAttr("disabled");
            }
        });
        gridConfigDocdet = {
            height: 370,
            width: 440,
            data: {},
            colNames: ["idsigma", "ddocumento", "ctipdocu", "dstipdocu", "mconfigdoc", "ctipestrdocu", "Item", "Dato", "tipdat"],
            colModel: [{
                    name: 'idsigma',
                    index: 'idsigma',
                    width: 0.01,
                    align: 'center',
                    hidden: true
                },
                {
                    name: 'ddocumento',
                    index: 'ddocumento',
                    width: 0.01,
                    align: 'left',
                    hidden: true
                },
                {
                    name: 'ctipdocu',
                    index: 'ctipdocu',
                    width: 0.01,
                    align: 'left',
                    hidden: true
                },
                {
                    name: 'dstipdocu',
                    index: 'dstipdocu',
                    width: 0.01,
                    align: 'left',
                    hidden: true
                },
                {
                    name: 'mconfigdoc',
                    index: 'mconfigdoc',
                    width: 0.01,
                    align: 'left',
                    hidden: true
                },
                {
                    name: 'ctipestrdocu',
                    index: 'ctipestrdocu',
                    width: 0.01,
                    align: 'left',
                    hidden: true
                },
                {
                    name: 'dstipestrdocu',
                    index: 'dstipestrdocu',
                    width: 150,
                    align: 'left'
                },
                {
                    name: 'vdatoitem',
                    index: 'vdatoitem',
                    width: 220,
                    align: 'left',
                    editable: true
                    /*,editoptions: {
                     dataInit: function(element,e) {
                     $(element).datepicker({dateFormat:"yy-mm-dd"});
                     }
                     }*/
                },
                {
                    name: 'tipdat',
                    index: 'tipdat',
                    width: 50,
                    hidden: true
                }
            ],
            onSelectRow: function(id) {
                //if(id && id!==lastsel){
                //jQuery('#tblResultDocdetalle').jqGrid('restoreRow',lastsel);
                //jQuery("#tblResultDocdetalle").jqGrid('saveRow',lastsel,true);
                //jQuery('#tblResultDocdetalle').jqGrid('editRow',id,false,DD_formatrow);
                //$("#"+id+"_vdatoitem").addClass("ui-text");
                //lastsel=id;
                //}
            },
            gridComplete: function() {
                var ids = jQuery(this).jqGrid('getDataIDs');
                for (var i = 0; i < ids.length; i++) {
                    $(this).editRow(ids[i], false, DD_formatrow);
                    //$("#"+ids[i]+"_vdatoitem").addClass("ui-text");
                }
            },
            editurl: 'clientArray',
            caption: " Datos del Documento",
            rowNum: 100,
            rownumbers: true
        };

        inicializarGrid("tblResultDocdetalle", gridConfigDocdet);
        /* btnInsertarDocdet = {
         caption: "Agregar&nbsp;&nbsp;",
         title: "Agregar Item",
         buttonicon: "ui-icon-plus",
         onClickButton: function() {
         
         }
         },
         btnEditarDocdet = {
         caption: "Editar&nbsp;&nbsp;",
         title: "Editar Item seleccionado",
         buttonicon: "ui-icon-pencil",
         onClickButton: function() {
         var gsr = $("#tblResultDocdetalle").jqGrid('getGridParam', 'selrow');
         if (gsr) {
         var row = jQuery("#tblResultDocdetalle").jqGrid('getRowData', gsr);
         
         } else {
         openDialogWarning("Seleccione la fila a editar.", 380, 150);
         }
         }
         },*/
        btnEliminarDocdet = {
            caption: "Eliminar&nbsp;&nbsp;",
            title: "Eliminar el Item seleccionado",
            buttonicon: "ui-icon-trash",
            onClickButton: function() {
                var gsr = $("#tblResultDocdetalle").jqGrid('getGridParam', 'selrow');
                if (gsr) {
                    var row = jQuery("#tblResultDocdetalle").jqGrid('getRowData', gsr);
                    openDialogConfirm1("\u00BFEst\u00E1 seguro de eliminar", 350, {
                        "Si": function() {

                        },
                        "No": function() {
                            closeDialog("jqDialogConfirmacion1");
                        }
                    });
                } else {
                    openDialogWarning("Seleccione la fila a eliminar.", 380, 150);
                }
            }
        };
        navPanelDocumentosdetalle();



        _gridConfigDocAdjunto = {
            height: 370,
            width: 440,
            colNames: ["idsigma", "ddocumento", "Nro.", "Adjunto", "Adjunto2", ""],
            colModel: [{
                    name: 'idsigma',
                    index: 'idsigma',
                    width: 100,
                    align: 'center',
                    hidden: true
                },
                {
                    name: 'ddocumento',
                    index: 'ddocumento',
                    width: 20,
                    align: 'left',
                    hidden: true
                },
                {
                    name: 'norden',
                    index: 'norden',
                    width: 50,
                    align: 'left'
                },
                {
                    name: 'vadjunto',
                    index: 'vadjunto',
                    width: 305,
                    align: 'left',
                    formatter: linkadjunto
                },
                {
                    name: 'vadjunto',
                    index: 'vadjunto',
                    width: 305,
                    align: 'left',
                    hidden: true
                },
                {
                    name: 'visor',
                    index: 'visor',
                    width: 20
                }
            ],
            caption: " Adjunto",
            rowNum: 1000,
            rownumbers: true
        };

        //inicializarGrid("DtblResultDocAdjunto", _gridConfigDocAdjunto);
        D_ProcesoBuscarDocAdjunto($("#Dddocumento").val());

    });

    function D_ProcesoBuscarDocAdjunto(pddocumento) {

        var paramtrs = '{' +
            '"pddocumento":"' + pddocumento + '"' +
            '}';

        parameters = {
            "name": "DtblResultDocAdjunto",
            "procedure": "coactivo.madjunto_get",
            "print": "true",
            "parameters": paramtrs
        };

        procesarConsultaSubProceso('registrar', parameters, D_procesoDocAdjunto, 'json');
    };

    function DD_formatrow(id) {
        var rowdat = jQuery("#tblResultDocdetalle").jqGrid('getRowData', id);

        var $textrow = $("#" + id + "_vdatoitem");
        $textrow.addClass("ui-text");
        if (rowdat.tipdat == 'DATE') {

            $("#" + id + "_vdatoitem").datepicker({
                showOn: "button",
                buttonImage: jQuery.scriptPath + "img/calendar.gif",
                buttonImageOnly: true,
                dateFormat: "dd/mm/yy"
            });
            $("#" + id + "_vdatoitem").css("width", "88%");
        }

        if (rowdat.tipdat == 'CTND') {


            var btnconten = $("<button>Contenido</button>").button({
                icons: {
                    primary: 'ui-icon-search'
                },
                text: false
            }).click(function() {


                $("#dialogOBS").html("<textarea id='textarOBSContent'>" + $textrow.val() + "</textarea>");
                var x_hEd = CKEDITOR.instances['textarOBSContent'];
                if (x_hEd) {
                    CKEDITOR.remove(x_hEd);
                }
                CKEDITOR.replace('textarOBSContent', config);

                $("#dialogOBS").dialog({
                    dialogClass: "no-close",
                    buttons: [{
                        text: "OK",
                        click: function() {
                            var x_oEditor = CKEDITOR.instances['textarOBSContent'];
                            var obs = x_oEditor.getData();
                            $textrow.val(obs);
                            $(this).dialog("close");
                        }
                    }]
                });



            });



            $textrow.parent().append(btnconten);
            $textrow.css("width", "80%");
        }

        if (rowdat.tipdat == 'PSNA') {


            var btnconten = $("<button>Persona</button>").button({
                icons: {
                    primary: 'ui-icon-person'
                },
                text: false
            }).click(function() {
                dobleclickPersona = function(row) {
                    //$("#find_administrado").val(row.cidpers);
                    //$("#show_administrado").val(row.cidpers + '  ' + row.crazsoc);
                    $textrow.val(row.crazsoc);
                    closeDialog("jqDialog2");
                };
                openDialogData2("mantenimientos/buscarpersona", null, "1000", "500", "Seleccione al administrado...");

            });


            //$("#"+id+"_vdatoitem").datepicker({dateFormat:"yy-mm-dd"});
            $textrow.parent().append(btnconten);
            $textrow.css("width", "80%");
        }

    }

    function D_procesoDocAdjunto(request) {
        var
            records = (request == null ? 0 : request.length),
            bindkeysDoc = {},
            _gridConfigDocAdjunto2 = $.extend(_gridConfigDocAdjunto, {
                data: request,
                datatype: "local",
                gridComplete: function() {
                    isGridComplete = true;
                    $("#DtblResultDocAdjunto").jqGrid('setSelection', 1, true);

                    var ids = jQuery("#DtblResultDocAdjunto").jqGrid('getDataIDs');

                    for (var i = 0; i < ids.length; i++) {
                        var cl = ids[i];
                        var rowdat = jQuery("#DtblResultDocAdjunto").jqGrid('getRowData', cl);
                        buttvisor = '<div title="Visor de ' + rowdat.vadjunto + '" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit"  onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\')" onclick="visorarchivo2(\'' + rowdat.ddocumento + '_' + rowdat.vadjunto + '\');"><span class="ui-icon ui-icon-search"></span></div>';


                        jQuery("#DtblResultDocAdjunto").jqGrid('setRowData', ids[i], {
                            visor: buttvisor
                        });
                    }

                }
            });

        $("#DpanelResultDocAdjunto").html('<table id="DtblResultDocAdjunto"></table><div id="pDtblResultDocAdjunto"></div>');
        inicializarGrid("DtblResultDocAdjunto", _gridConfigDocAdjunto2);


    };



    function navPanelDocumentosdetalle() {
        $("#tblResultDocdetalle").jqGrid('navGrid', '#ptblResultDocdetalle', {
            edit: false,
            add: false,
            del: false,
            search: false,
            refresh: false
        });
        /* $("#tblResultDocdetalle").jqGrid('navButtonAdd', '#ptblResultDocdetalle', btnInsertarDocdet);
          $("#tblResultDocdetalle").jqGrid('navSeparatorAdd', '#ptblResultDocdetalle');
         $("#tblResultDocdetalle").jqGrid('navButtonAdd', '#ptblResultDocdetalle', btnEditarDocdet);
         $("#tblResultDocdetalle").jqGrid('navSeparatorAdd', '#ptblResultDocdetalle');*/
        //$("#tblResultDocdetalle").jqGrid('navButtonAdd', '#ptblResultDocdetalle', btnEliminarDocdet);
    };

    function ProcesoBuscarDocdet(vctipdocu) {

        var paramtrs = '{' +
            '"ddocumento":"<?php echo $this->ddocumento; ?>",' +
            '"ctipdocu":"' + vctipdocu + '"' +
            '}';

        parameters = {
            "name": "tblResultDoc",
            "procedure": "Coactivo.ddocumestr_get",
            "print": "true",
            "parameters": paramtrs
        };

        procesarConsultaSubProceso('registrar', parameters, procesoDocdet, 'json');
    };

    function procesoDocdet(request) {
        var
            records = (request === null ? 0 : request.length),
            gridConfigDocdet2 = $.extend(gridConfigDocdet, {
                data: request,
                datatype: "local"
            });

        $("#paneltblResultDocdetalle").html('<table id="tblResultDocdetalle"></table><div id="ptblResultDocdetalle"></div><input type="hidden" id="ctblResultDocdetalle" name="ctblResultDocdetalle" value="' + records + '" />');
        inicializarGrid("tblResultDocdetalle", gridConfigDocdet2, {});
        navPanelDocumentosdetalle();

    };

    function DdocumentoSave(type) {
        //$("#sestGrid").clearGridData(false);

        var vcbotipodoc = $("#cbotipodoc").val();
        var vcborelevancia = $("#cborelevancia").val();
        var vtxtnrodoc = $("#txtnrodoc").val();
        var vtxtfolios = $("#txtvfolios").val(); //MODIFICADO 0106
        //MODIFICADO 0106
        if (vtxtfolios === '') {
            openDialogError("Ingresar numero de folios", "250", "150", function() {
                $("#txtvfolios").focus();
            });
            return;
        }
        if (vtxtfolios == '0') {
            openDialogError("La cantidad e Folios no puede ser 0", "250", "150", function() {
                $("#txtvfolios").focus();
            });
            return;
        }
        if (vcbotipodoc === '9999999999') {
            openDialogError("Seleccionar tipo de documento", "250", "150", function() {
                $("#linktipodoc").focus();
            });
            return;
        }
        if (!($('#chknrodoc').is(":checked"))) {
            if (vtxtnrodoc === '') {
                openDialogError("Ingresar numero de documento", "250", "150", function() {
                    $("#txtnrodoc").focus();
                });
                return;
            }
        }
        if (vcborelevancia === '9999999999') {
            openDialogError("Seleccionar relevancia del documento", "250", "150", function() {
                $("#linkrelevancia").focus();
            });
            return;
        }


        var ids = jQuery("#tblResultDocdetalle").jqGrid('getDataIDs');
        for (var i = 0; i < ids.length; i++) {
            $('#tblResultDocdetalle').jqGrid('saveRow', ids[i], false, 'clientArray');
            var row = jQuery("#tblResultDocdetalle").jqGrid('getRowData', ids[i]);
            //console.log(row);

        }
        var rows = jQuery("#tblResultDocdetalle").jqGrid('getRowData');
        //console.log(JSON.stringify(rows));

        var oEditor = CKEDITOR.instances['txtobservacion'];
        var obs = oEditor.getData();

        var parmter = {};
        parmter.type = type;
        parmter.pidsigma = $('#Dddocumento').val();
        parmter.pctipdocu = $("#cbotipodoc").val();
        parmter.pvnrodocu = $("#txtnrodoc").val();
        parmter.pvfolios = $("#txtvfolios").val(); //MODIFICADO 0106
        parmter.pvobserv = obs;
        parmter.pctiprele = $("#cborelevancia").val();
        parmter.pctipjerar = $("#Dctipjerar").val();
        parmter.pcidsigma = $("#Dcidsigma").val();
        parmter.detalle = JSON.stringify(rows);
        parmter.pchknrodoc = $('#chknrodoc').is(":checked") ? "1" : "0";
        parmter.ccate = $('#Dccate').val();
        parmter.pfecingresodoc = $('#txtfecingresodoc').val();
        $.post(path + "documentos/ddocumentomantesave", parmter, updateresultDdocumento, 'json');


    }

    function updateresultDdocumento(data) {
        manualuploader.uploadStoredFiles();

        openDialogInfo(data[0].msj, "250", "150", null, function() {
            //data[0].ddocument;
            closeDialog("jqDialog3");
            ProcesoBuscarDoc();
        });
        //console.log(data);
    }



    function linkadjunto(cellvalue, options, rowObject) {
        return '<a href="#" onclick="linkadjuntoOpen(\'' + options.rowId + '\',\'' + cellvalue + '\')" > ' + cellvalue + '</a>'
    }

    function linkadjuntoOpen(rowId, cellvalue) {

        var row = jQuery("#DtblResultDocAdjunto").jqGrid('getRowData', rowId);

        //console.log(row);
        window.open(path + "documentos/forzardescarga?file=" + row.ddocumento + '_' + cellvalue);
    }

    function visorarchivo2(nom_archivo) {
        /*openDialogDataFunction1("documentos/ddocumentomante", { type: "M", ddocument: row.idsigma,cidsigma :$('#cidsigma').val(),ctipjerar: $('#ctipjerar').val() }, "980", "630", "Modificar Documento " + row.dstipdocu, null, { 'Aceptar': function() { DdocumentoSave('M'); }, 'Cancelar': function() { closeDialog("jqDialog1"); } });*/
        //http://localhost:81/titaniaSQL/public/uploadDdocuments/
        //console.log(jQuery.scriptPath+'uploadDdocuments/'+nom_archivo);
        var page = '';
        arrarchivo = nom_archivo.split(".");
        extarchivo = arrarchivo[1];

        if (extarchivo == 'png' || extarchivo == 'jpg' || extarchivo == 'gif') {

            if (navigator.appName == 'Microsoft Internet Explorer') {

                var ver = getInternetExplorerVersion();
                if (ver > -1) {
                    // alert(ver);
                    if (ver <= 9.0) {
                        page = jQuery.scriptPath + 'uploadDdocuments/' + nom_archivo;
                        var $dialog = $('<div></div>')
                            .html('<div align="center"><iframe style="border: 0px; " src="' + page + '" width="700" height="600"></iframe></div>')
                            .dialog({
                                autoOpen: false,
                                modal: true,
                                height: 700,
                                width: 800,
                                title: "Visor de Archivos"
                            });
                        $dialog.dialog('open');

                    }
                } else {
                    page = path + "documentos/visordocs?img=" + nom_archivo;
                    var $dialog = $('<div></div>')
                        .load(page)
                        .dialog({
                            autoOpen: false,
                            modal: true,
                            height: 650,
                            width: 800,
                            title: "Visor de Archivos"
                        });
                    $dialog.dialog('open');


                }
            } else {

                page = path + "documentos/visordocs?img=" + nom_archivo;
                var $dialog = $('<div></div>')
                    .load(page)
                    .dialog({
                        autoOpen: false,
                        modal: true,
                        height: 650,
                        width: 800,
                        title: "Visor de Archivos"
                    });
                $dialog.dialog('open');

            }




        } else {
            page = jQuery.scriptPath + 'uploadDdocuments/' + nom_archivo;
            var $dialog = $('<div></div>')
                .html('<div align="center"><iframe style="border: 0px; " src="' + page + '" width="700" height="600"></iframe></div>')
                .dialog({
                    autoOpen: false,
                    modal: true,
                    height: 700,
                    width: 800,
                    title: "Visor de Archivos"
                });
            $dialog.dialog('open');
        }
    }
</script>