<!DOCTYPE html>
<html lang="en">
	<head>

<!--		<link href="http://localhost/titania_tramite/public/css/visor/jquery.fs.zoomer.css" rel="stylesheet" type="text/css">
		<script type="text/javascript" src="http://localhost/titania_tramite/public/js/app/ui/01_jquery-1.8.2.min.js"></script>
		<script type="text/javascript" src="http://localhost/titania_tramite/public/js/app/visor/jquery.fs.zoomer.js"></script>
	-->
	<style>
    .zoomer_wrapper {
        border: 1px solid #ddd;
        border-radius: 3px;
        height: 600px;
        margin: 0px 0;
        overflow: hidden;
        width: 100%;
    }
    </style>

	<script type="text/javascript">
        $(document).ready(function() {
            $(".zoomer_wrapper").zoomer();
/*
            $(".zoomer_custom").zoomer({
                controls: {
                    zoomIn: ".zoomer_custom_zoom_in",
                    zoomOut: ".zoomer_custom_zoom_out"
                },
                customClass: "dark_zoomer",
                increment: 0.03,
                interval: 0.1,
                marginMax: 50
            });
			*/

/*
            $(window).on("resize", function(e) {
                $(".zoomer_wrapper").zoomer("resize");
            });
	*/	
	//$(".zoomer_basic").zoomer("load", "<?php echo $this->util()->getImageAdjunto($this->img); ?>");
        });		
    </script>
	</head>
	<body>
	
    <div class="mobile-full tablet-full desktop-8 desktop-push-2">
        <div class="zoomer_wrapper zoomer_basic">
           <img id="ImgID" src="<?php echo $this->util()->getImageAdjunto($this->img); ?>">
        </div>
    </div>
	</body>
</html>