<div id="panelbusqueda" align="center" class="ui-widget ui-widget-content ui-corner-all "  style="width: 99%;margin: 5px ; ">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <table border="0" width="100%" >
            <tr >
                <td width="3%">
                    <a href="../coactivo/index">
                        <img width="25" height="25" src="<?php echo $this->util()->getImage("home-icon.png");?>">
                    </a></td>
                <td align="center" width="97%">
                    <label style="font-size:12px !important;">CONSULTAS</label>
                </td>
            </tr>
        </table>
    </div>
	<input type="hidden" value="<?php echo $this->cidusuario?>"  id="hdcidusuario"/>
    <table border="0" width="80%">

        <tr >
            <td width="150px"> &nbsp;</td>
            <td  width=120><b>Cntribuyente  </b></td>

            <td rowspan="2">  <button id="btnbuscardocsUser">Buscar</button> </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="text" id="contrib" class="ui-text" style="text-align: left;width: 100px;"/>
            </td>


        </tr>
        <!-- <tr><td colspan="5">&nbsp;</td></tr> -->
    </table>
   
</div>
<div id="panelDocUser" >
        <table id="tblDocUser"></table><div id="ptblDocUser"></div>
</div>

    <script>
    $(document).ready(function() {

        $("#btnbuscardocsUser").button({ icons: { primary: "ui-icon-search"} }).click(function() { ProcesoBuscarDocsuser(); });

        $("#fecdesde").datepicker({ showOn: "button", buttonImage: pathImage + "calendar.gif", buttonImageOnly: true, dateFormat: "dd/mm/yy" });
        $("#fechasta").datepicker({ showOn: "button", buttonImage: pathImage + "calendar.gif", buttonImageOnly: true, dateFormat: "dd/mm/yy" });

        gridConfigDocsUser = {
                height: 230,
                width: 875,
                colNames: ["cdruta", "mruta","musuario","Nro Documento", "ctipacc","Accion","Fec.Envio","Fec.Recep","","Fec Devol","","vobserv","mruta","mdocumento","Ruta","Docs."],
                colModel: [
                    { name: 'cdruta', index: 'cdruta', width: 100, align: 'center',hidden: true },
                    { name: 'cmruta', index: 'cmruta',  align: 'left' ,hidden: true},
                    { name: 'musuario', index: 'musuario', width: 100, align: 'left',hidden: true},
                    { name: 'vnrodocu', index: 'vnrodocu', width: 150, align: 'left' },
                    { name: 'ctipacc', index: 'ctipacc', width: 130, align: 'left' ,hidden: true},
                    { name: 'vtipacc', index: 'vtipacc', width: 120, align: 'left' },
                    {name: 'dfecenv', index: 'dfecenv', width: 100, align: 'center'},
                    {name: 'dfecrecep', index: 'dfecrecep', width: 100, align: 'center'},
                    { name: 'st_recep', index: 'st_recep', width: 20, align: 'center', formatter: chkFormatrecep },
                    { name: 'dfecdevol', index: 'dfecdevol', width:100, align: 'center'},
                    { name: 'st_devol', index: 'st_devol', width: 20, align: 'center', formatter: chkFormatdevol },
                    { name: 'vobserv', index: 'vobserv', width: 100, align: 'center',hidden: true },
                    { name: 'mruta', index: 'mruta', width: 100, align: 'center',hidden: true },
                   
                   { name: 'mdocumento', index: 'mdocumento', width: 200, align: 'left',hidden: true },
                   { name: 'btnmruta', index: 'btnmruta', width: 40, align: 'center' ,formatter : btnruta},
                    { name: 'btndocumt', index: 'btndocumt', width: 40, align: 'center' ,formatter : btndocumt}
                    ],
                caption: " Bandeja Documentos del Usuario",
                rowNum: 10,
                rownumbers: true,
                
                viewrecords: true,
                recordpos: 'right',
                loadComplete: function (data) {
                    if (data.rows.length > 0) {
                        
                       /* for (var i = 0; i < data.rows.length; i++) {
                            //console.log(data.rows[i]);
                            if (data.rows[i].bnd=='S') {
                                $("#jqg_tblDocUser_" + (i+1)).css("visibility", "hidden");
                                
                                $("#chkrecep_" + (i+1)).attr("disabled", "disabled");
                            }

                        }*/
                    }
                    
                    $("#cb_tblDocUser").css("visibility", "hidden");
                },
                onSelectRow: function(id){
                        /*console.log(id);
                        var row = jQuery("#tblDocUser").jqGrid('getRowData', id);
                        //console.log(row);
                        if (row.bnd=='S')
                            jQuery("#tblDocUser").jqGrid('setSelection',id);
                        */
                }
            };

            inicializarGrid("tblDocUser", gridConfigDocsUser);
            //navPanelRuta();

        });

 
     ProcesoBuscarDocsuser = function() {
        //var paramtrs = '[{"0":"dve"},{"1":"dve"}]';
        var paramtrs = '['+
                        '["@pmusuario","'+$('#hdcidusuario').val()+'"],'
                        +'["@pfdesde","'+$('#fecdesde').val()+'"],'
                        +'["@pfhasta","'+$('#fechasta').val()+'"]'
                        +']';

        parameters = {
        "name": "tblDocUser",
        "procedure": "tramite.sp_druta_get",
        "print" :"true",
        "parameters": paramtrs
        };
        
        procesarConsultaSubProceso('registrar', parameters, procesoRuta, 'json');
    };
    procesoRuta = function(request){
        var records = (request == null ? 0 : request.length),
        gridConfigDocsUser2 = $.extend(gridConfigDocsUser, {
            data: request,
            datatype: "local"
        });

        $("#panelDocUser").html('<table id="tblDocUser"></table><div id="ptblDocUser"></div>');
        inicializarGrid("tblDocUser", gridConfigDocsUser2, {});
        //navPanelRuta();
        
    };
 
 // -----> btnruta
 function btnruta(cellvalue, options, rowObject){
    
        return '<div class="ui-pg-button " title="Ver Ruta" style="text-align:center;float: left; cursor: pointer; display: block;" onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" onclick="accionbtnruta(\''+options.rowId+'\');"><div class="ui-pg-div  ui-inline-edit" ><span class="ui-icon ui-icon-search"></span></div></div>';
    }
    function accionbtnruta(rowId){


        var rowdat = jQuery("#tblDocUser").jqGrid('getRowData',rowId);
        
        var paramtrs ={ mruta :rowdat.mruta };

        openDialogDataFunction1("documentos/hojaruta", paramtrs, "1150", "600", "Hoja de Ruta " , null, {});


    }
 // <------  btnruta
 
 // -----> btndocumt Boton que llama a los documentos del documento
    function btndocumt(cellvalue, options, rowObject){
    	//console.log(rowObject);
  		return '<div align="center" class="ui-pg-button " title="Documentos" style="text-align:center;float: left; cursor: pointer; display: block;" onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" onclick="accionbtndocumt(\''+options.rowId+'\');"><div class="ui-pg-div  ui-inline-edit" ><span class="ui-icon ui-icon-document-b"></span></div></div>';
        
    }

    function accionbtndocumt(rowId){
        var rowdat = jQuery("#tblDocUser").jqGrid('getRowData',rowId);
        //console.log($(rowdat.st_devol).is(":checked"));
        var isedit ='1'; // Editable
        if($(rowdat.st_devol).is(":checked")){
            isedit='0'; // No es editable
        }

        var paramtrs ={ 
            cidsigma :rowdat.cdruta 
            ,ctipjerar: '0000000132'
            ,mdocumento:rowdat.mdocumento
            ,editable :isedit
        };

        openDialogDataFunction1("documentos/ddocumento", paramtrs, "1000", "520", "Documentos " , null, {});
    }

 // <------- btndocumt

  // ----> ChkBox Recepcionado

    function chkFormatrecep(cellvalue, options, rowObject) {
        return '<input  type="checkbox" id="chkrecep_'+options.rowId+'" ' + (cellvalue=='1' ? ' checked="checked"' : '') +
            'onclick="changecheckboxrecepdevol(' + options.rowId + ',1)" ' + (cellvalue=='1' ? ' disabled ' : '') + '/>';
    }

    function changecheckboxrecepdevol(rowId,type) {
	msjconfir='';
	var row = jQuery("#tblDocUser").jqGrid('getRowData', rowId);
	if (type==1){
		msjconfir=' Recepcionar ';
		}
	if (type==2){
		//console.log($(row.st_recep).is(':checked'));
		if ($(row.st_recep).is(':checked')==false){
			openDialogWarning("Documento NO recepcionado.",undefined,ProcesoBuscarDocsuser);
			return;
			}
		
		msjconfir=' Devolver ';
		}
		 
    
        openDialogConfirm1("\u00BFEst\u00E1 seguro de "+msjconfir+" el Documento?", 350, {
        "Si": function() {
                var parmter = {};
                parmter.ptype = type,
                parmter.pcdruta = row.cdruta;
                closeDialog("jqDialogConfirmacion1");
                $.post(path + "documentos/drutarecepdevol", parmter, updCheckrecepdevol, 'json');
            },
            "No": function() {
            	ProcesoBuscarDocsuser();
                closeDialog("jqDialogConfirmacion1");
                
            }
        });
            
            
    }

    var updCheckrecepdevol = function(data) {
    //console.log(data);
    	/*{ "Aceptar": function() { closeDialog("jqDialogInfo"); }} */
    openDialogInfo(data[0].msj, "250", "150", null, ProcesoBuscarDocsuser);
    };

//  ChkBox Recepcionado <----


function chkFormatdevol(cellvalue, options, rowObject) {
    return '<input  type="checkbox" id="chkrecep_'+options.rowId+'" ' + (cellvalue=='1' ? ' checked="checked"' : '') +
        'onclick="changecheckboxrecepdevol(' + options.rowId + ',2)" ' + (cellvalue=='1' ? ' disabled ' : '') + '/>';
}

</script>
