<div align="center"   style="width:1200px; height:580px;  background:url(<?php echo $this->util()->getImage('fondo_git.jpg'); ?>); background-position:center;" >
	<table style="width: 50%; " border="0" cellspacing="0" cellpadding="0" align="right">
		<tr>
			<td width="30">&nbsp;</td>
			<td width="26">&nbsp;</td>
			<td width="64">&nbsp;</td>
			<td width="50">&nbsp;</td>
			<td width="30">&nbsp;</td>
		</tr>
		<tr>
			<td width="30">&nbsp;</td>
			<td width="26">&nbsp;</td>
			<td width="64">&nbsp;</td>
			<td width="50">&nbsp;</td>
			<td width="30">&nbsp;</td>
		</tr>
		<tr>
			<td width="30">&nbsp;</td>
			<td width="26">&nbsp;</td>
			<td width="64">&nbsp;</td>
			<td width="50">&nbsp;</td>
			<td width="30">&nbsp;</td>
		</tr>
		<tr>
			<td width="30">&nbsp;</td>
			<td width="26">&nbsp;</td>
			<td width="64">&nbsp;</td>
			<td width="50">&nbsp;</td>
			<td width="30">&nbsp;</td>
		</tr>
		<tr>
			<td width="30">&nbsp;</td>
			<td width="26">&nbsp;</td>
			<td width="64">&nbsp;</td>
			<td width="50">&nbsp;</td>
			<td width="30">&nbsp;</td>
		</tr>
		<tr>
			<td width="30">&nbsp;</td>
			<td width="26">&nbsp;</td>
			<td width="64">&nbsp;</td>
			<td width="50">&nbsp;</td>
			<td width="30">&nbsp;</td>
		</tr>
		<tr>
			<td width="30">&nbsp;</td>
			<td width="26">&nbsp;</td>
			<td width="64">&nbsp;</td>
			<td width="50">&nbsp;</td>
			<td width="30">&nbsp;</td>
		</tr>
			<tr>
			<td width="30">&nbsp;</td>
			<td width="26">&nbsp;</td>
			<td width="64">&nbsp;</td>
			<td width="50">&nbsp;</td>
			<td width="30">&nbsp;</td>
		</tr>
		<tr>
			<td width="30">&nbsp;</td>
			<td width="26">&nbsp;</td>
			<td width="64">&nbsp;</td>
			<td width="50">&nbsp;</td>
			<td width="30">&nbsp;</td>
		</tr>
		<tr>
			<td width="30">&nbsp;</td>
			<td width="26">&nbsp;</td>
			<td width="64">&nbsp;</td>
			<td width="50">&nbsp;</td>
			<td width="30">&nbsp;</td>
		</tr>
		<tr>
			<td width="30">&nbsp;</td>
			<td width="26">&nbsp;</td>
			<td width="64">&nbsp;</td>
			<td width="50">&nbsp;</td>
			<td width="30">&nbsp;</td>
		</tr>
		<tr>
			<td width="30">&nbsp;</td>
			<td width="26">&nbsp;</td>
			<td width="64">&nbsp;</td>
			<td width="50">&nbsp;</td>
			<td width="30">&nbsp;</td>
		</tr>
		<tr>
			<td width="30">&nbsp;</td>
			<td width="26">&nbsp;</td>
			<td width="64">&nbsp;</td>
			<td width="50">&nbsp;</td>
			<td width="30">&nbsp;</td>
		</tr>
		<tr>
			<td colspan="5">
			<div id="div_resp_logeo" align="center"></div>
			</td>
		</tr>
		<tr style="display: none;">
			<td>&nbsp;</td>
			<td aling="left">Local:</td>
			<td colspan="2">
				<select style="width: 190px;" id="cboLocal" tabindex="1">
					<?php echo $this->util()->getComboContenedor('1000000346', '1000000347'); ?>
				</select>
				<!-- autocomplete="off" -->
			</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td aling="left">Usuario:</td>
			<td colspan="2">
				<input class="ui-text" type="text" id="txtuser" name="txtuser" value="" size="19" placeholder="Usuario" tabindex="2">
				<!-- autocomplete="off" -->
				<input type="button" id="btningreso" name="btningreso" value="Ingresar" tabindex="4">
			</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td aling="left">Contrase&ntilde;a:</td>
			<td colspan="2">
				<input class="ui-text" type="password" id="txtpass" name="txtpass" value="" size="19" placeholder="Contrase&ntilde;a"  tabindex="3">
				<!-- autocomplete="off" -->
				
			</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<!--
		<tr>
			<td>&nbsp;</td>
			<td colspan="3">Nivel:</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td colspan="2">
			<select id="cbnivel" name="cbnivel">
				<option value="0">Trabajador</option>
			</select>
			</td>
			<td>&nbsp;</td>
		</tr>
		-->
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td colspan="3" align="center">
				
			</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</table>
</div>