<div id="panelbusqueda" align="left" class="ui-widget ui-widget-content ui-corner-all "
     style="width: 98.8%;margin-top:2px;margin-left : 0px;margin-right :0px;margin-bottom:2px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <table border="0" width="100%" >
            <tr >
                <td width="3%">
                    <A href="index">
                        <img width="25" height="25" src="<?php echo $this->util()->getImage("home-icon.png");?>">
                </A></td>
                <td align="center" width="97%">
                    <label style="font-size:12px !important;">AUXILIARES COACTIVOS</label>
                </td>
            </tr>
        </table>
    </div>

</div>


<div id="dvbusqueda">
    <div id="dvaccion"></div>
    <br/>
    <div id="panelResultauxiliares">
        <table id="tblResultauxiliares"></table>
        <div id="ptblResultauxiliares"></div>
    </div>
    <br/>
</div>
