<?php
$userdata = new Zend_Session_Namespace('datosuserlog');
?>
<table class="ui-table-panelLayout" style="width: 90%; height: 100%; font-size: 90%;" border="0">
    <tr id="trbuttonadministrado">
        <td colspan="3">
            <button type="button" id="btnbuscaradministrado" name="btnbuscaradministrado" onclick="seleccionarPersona()">
                Buscar Contribuyente
            </button>
        </td>
    </tr>

    <!-- Administrado -->
    <tr class="xperson">
        <td style="text-align:left;">
            C&oacute;digo:
        </td>
        <td style="text-align:left;"><b><span id="showidperson" name="showidperson"><?php echo $this->mperson; ?></span></b>
            <input type="hidden" id="hdmperson" name="hdmperson" value="<?php echo $this->mperson; ?>" />
            <input type="hidden" id="hdctipper" name="hdctipper" value="<?php echo $this->ctipper; ?>" />
        </td>
        <td rowspan="5" align="center" valign="top">
            <img style="width: 85px; height: 105px; border: 1px solid #000;" src="<?php echo $this->util()->getPhoto($this->mperson); ?>" />
        </td>
    </tr>
    <tr class="xperson">
        <td style="text-align:left;">
            Nombre :
        </td>
        <td style="text-align:left;">
            <b><span id="showvperson" name="showvperson"><?php echo $this->vperson; ?></span></b>
        </td>
    </tr>
    <tr class="xperson">
        <td style="text-align:left;">
            Documento :
        </td>
        <td style="text-align:left;">
            <b><span id="showvdocper" name="showvdocper"><?php echo $this->vdocper; ?></span></b>
        </td>
    </tr>
    <tr class="xperson">
        <td style="text-align:left;">
            Direcci&oacute;n :
        </td>
        <td style="text-align:left;">
            <b><span id="showvdirecc" name="showvdirecc"><?php echo $this->vdirecc; ?></span></b>
        </td>
    </tr>
    <tr class="xperson">
        <td colspan="2">Tramites en proceso:</b></td>
    </tr>
    <tr class="xperson">
        <td colspan="2">
            <hr />
        </td>
    </tr>
    <!-- Representante Legal -->
    <tr class="clsrespon" id="trbuttonrepresentante">
        <th colspan="2">
            <button type="button" id="btnbuscarrepresentante" name="btnbuscarrepresentante" onclick="seleccionarRepresentante()">
                Buscar Representante Legal
            </button>
        </th>
    </tr>
    <tr class="clsrespon">
        <td style="text-align:left;">
            C&oacute;digo:&nbsp;
        </td>
        <td style="text-align:left;">
            <b><span id="showcrepres" name="showcrepres"><?php echo $this->crepres; ?></span></b>
            <input type="hidden" id="hdcrepres" name="hdcrepres" value="<?php echo $this->crepres; ?>" />
        </td>
        <td rowspan="5" align="center" valign="top">

        </td>
    </tr>
    <tr class="clsrespon">
        <td style="text-align: left;">
            Nombre :
        </td>
        <td style="text-align: left;">
            <b><span id="showvrepres" name="showvrepres""><?php echo $this->vrepres; ?></span></b>
        </td>
    </tr>
    <tr class=" clsrespon">
        <td style="text-align: left;">
            Documento :
        </td>
        <td style="text-align: left;">
            <b><span id="showvdocrep" name="showvdocrep""><?php echo $this->vdocrep; ?></span></b>
        </td>
    </tr>

<!--
    <tr class=" clsentrega3">
        <th colspan="2">
            <input type="hidden" id="hdflagentrega" name="hdflagentrega" value="<?php echo $this->flagdentrega; ?>" />
            Escribir <input type="checkbox" id="chkflagdentrega" name="chkflagdentrega" <?php echo ($this->flagdentrega == '1') ? 'checked' : ''; ?> />
            <br /><br />
        </th>
    </tr>
    -->
    <tr class=" clsentrega4">
        <th colspan="3">
            <b style="font-size: 11px;">Ingresar Valor</b>
        </th>
    </tr>

    <tr class="clsentrega2">
        <th colspan="3"> Valor :
            <textarea id="txtdentrega" name="txtdentrega" style="max-width: 180px;min-width: 180px;" rows="2" class="editable ui-text"><?php echo $this->dentrega; ?></textarea>
        </th>
    </tr>

    <!-- Persona que entrega el documento -->
    <tr class=" clsentrega4">
        <th colspan="3">
            <b style="font-size: 11px;">Persona que entrega el documento</b>
        </th>
    </tr>
    <tr class="clsentrega" id="trbuscarentrega">
        <th colspan="2">
            <button type="button" id="btnbuscarentrega" name="btnbuscarentrega" onclick="seleccionarEntregante()">
                Buscar
            </button>
        </th>
    </tr>
    <tr class="clsentrega">
        <td style="width:80px;text-align:left;">
            C&oacute;digo:&nbsp;
        </td>
        <td style="text-align:left;">
            <b><span id="showcentrega" name="showcentrega"><?php echo $this->centrega; ?></span></b>
            <input type="hidden" id="hdcentrega" name="hdcentrega" value="<?php echo $this->centrega; ?>" />
        </td>

    </tr>
    <tr class="clsentrega">
        <td style="text-align:left;">
            Nombre :
        </td>
        <td style="text-align:left;">
            <b><span id="showventrega" name="showventrega"><?php echo $this->ventrega; ?></span></b>
        </td>
    </tr>
</table>

<script type="text/javascript">
    <?php if ($this->buttons == "") { ?>
        $("#trbuttonadministrado").css("display", "none");
        $("#trbuttonrepresentante").css("display", "none");
        $("#trbuscarentrega").css("display", "none");
        $("#btnbuscaradministrado").hide();
        $("#btnbuscarrepresentante").hide();
        $("#btnbuscarentrega").hide();
        $(".clsentrega3").hide();
        $("#txtdentrega").css('background-color', 'lightgray');
        $("#txtdentrega").attr('readonly', 'readonly');

        if ($("#showidperson").html() === '0000000001') {
            $(".xperson").hide();
        }

        if ($.trim($("#txtdentrega").val()) === "" && $.trim($("#hdcentrega").val()) === "") {
            $(".clsentrega").hide();
            $(".clsentrega4").hide();
        }
    <?php } ?>
    //$("#chkflagdentrega").hide();

    function registro_dentrega() {
        if ($("#chkflagdentrega").attr('checked')) {
            $(".clsentrega2").show();
            $(".clsentrega").hide();
            $("#hdflagentrega").val(1);
        } else {
            $(".clsentrega2").hide();
            $(".clsentrega").show();
            $("#hdflagentrega").val(0);
        }
    }
    //registro_dentrega();
    /*
        $("#chkflagdentrega").change(function() {
            registro_dentrega();
        });*/

    $("#btnbuscaradministrado").button({
        icons: {
            primary: 'ui-icon-search'
        },
        text: true
    });
    $("#btnbuscarrepresentante").button({
        icons: {
            primary: 'ui-icon-search'
        },
        text: true
    });
    $("#btnbuscarentrega").button({
        icons: {
            primary: 'ui-icon-search'
        },
        text: true
    });

    var vctipper = $("#hdctipper").val();
    if (vctipper != '0000000121') {
        $(".clsrespon").css("display", "none");
    }
    var dobleclickPersona = function() {

    };

    function quitardatosRepresentante() {
        $("#hdcrepres").val("");
        $("#showcrepres").html("");
        $("#showvrepres").html("");
        $("#showvdocrep").html("");
    }

    function seleccionarPersona() {
        dobleclickPersona = function(row) {
            var mpersonPrevio = $("#hdmperson").val();
            var crepresPrevio = $("#hdcrepres").val();

            $("#hdmperson").val(row.cidpers);
            $("#hdctipper").val(row.ctipper);
            $("#txtvperson").val(row.crazsoc);
            $("#showidperson").html(row.cidpers);
            $("#showvperson").html(row.crazsoc);
            $("#showvdocper").html(row.vnrodoc);
            $("#showvdirecc").html(row.direccf);
            if (row.ctipper == "0000000121") {
                $(".clsrespon").fadeIn();
            } else {
                $(".clsrespon").fadeOut();
            }
            quitardatosRepresentante();

            if ($("#hdmperson").val() == $("#hdcentrega").val()) {
                $("#hdcentrega").val("");
                $("#showcentrega").html("");
                $("#showventrega").html("");
            }

            closeDialog("jqDialog1");
        }
        openDialogData1("coactivo/buscarpersona", null, "1000", "500", "Seleccione el Contribuyente...");
    }

    function seleccionarRepresentante() {
        dobleclickPersona = function(row) {
            if (row.cidpers == $("#hdmperson").val()) {
                openDialogWarning("No puede seleccionar el Contribuyente como su propio representante legal.");
                return;
            }
            $("#hdcrepres").val(row.cidpers);
            $("#showcrepres").html(row.cidpers);
            $("#showvrepres").html(row.crazsoc);
            $("#showvdocrep").html(row.vnrodoc);
            closeDialog("jqDialog1");
            if ($("#hdcrepres").val() == $("#hdcentrega").val()) {
                $("#hdcentrega").val("");
                $("#showcentrega").html("");
                $("#showventrega").html("");
            }
        };
        openDialogData1("coactivo/buscarpersona", null, "1000", "500", "Seleccione el Contribuyente...");
    }

    function seleccionarEntregante() {
        dobleclickPersona = function(row) {
            if (row.cidpers == $("#hdmperson").val()) {
                openDialogWarning("Ya esta seleccionado como remitente.");
                return;
            }
            $("#hdcentrega").val(row.cidpers);
            $("#showcentrega").html(row.cidpers);
            $("#showventrega").html(row.crazsoc);
            closeDialog("jqDialog1");
        };
        openDialogData1("coactivo/buscarpersona", null, "1000", "500", "Seleccione persona que entrega el documento...");
    }
</script>