

<div align="center" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Mantenimiento de Objetos</label>
    </div>
    <table style="width: 100%; height: 492px; padding-bottom: 2px;" border="0" cellpadding="0" cellspacing="0">
        <tr>
            <td rowspan='2' style="width: 300px">
                <br/>
                <div id="tree-mconten" align="left" style="overflow:scroll; height: 452px; width:300px; border:1px solid #c3daf9;"></div>
            </td>
            <td style="vertical-align: top;" width="720px">
                <div id="cont_form"></div>
            </td>
            <td style="vertical-align:middle;">
                <button id="btnnuevonodo" style="width: 145px;">Nuevo Objeto</button></br></br>
                <button id="btnaniadirnodo" >A&ntilde;adir Objeto Hijo</button></br></br>
                <button id="btnguardarmcontennodo" style="width: 145px;">Guardar</button></br></br>
                <button id="btnimprimir" style="width: 145px;" value="-1" onclick="imprimirmconten(this.value);" >Imprimir</button></br></br>
                <button id="btnbotones" style="width: 145px;">Botones</button></br></br>
            </td>
        </tr>

</table>
</div>
<script>
    $("#btncambiaresquema").button({icons:{primary:"ui-icon-search"},text:false});
    $("#btnnuevonodo").button({icons:{primary:"ui-icon-plusthick"}});
    $("#btnaniadirnodo").button({icons:{primary:"ui-icon-plusthick"}});
    $("#btnbotones").button({icons:{primary:"ui-icon-plusthick"}});
    $("#btnguardarmcontennodo").button({icons:{primary:"ui-icon-disk"}});
    $("#btnimprimir").button({icons:{primary:"ui-icon-calculator"}});
    $('#btnguardarmcontennodo').unbind('click');
    $('#btnguardarmcontennodo').bind('click', objetossave);
    $('#btnbotones').bind('click', agregarBotones);

    //$('#btnbotones').button('option', 'disabled', true);

    /*$(function(){
        var cod = $('#c_codigo').html();
        alert(cod);
        if (cod == undefined) {
            $('#btnbotones').button('option', 'disabled', true);
        } else {

        }
    });*/

</script>