
<style>
    table.mconten tr td {
        padding-top: 2px;
        padding-bottom: 2px;
    }
</style>
<div style="width:568px;">
    <div id="div_mensaje"></div>
    <br/>
    <table class="mconten" align="center" style="width: 550px" border="0" cellspacing="0" cellpadding="0"
           style="padding-top: 5px;">
        <tr>
            <td style="width: 150px;text-align: left; padding-left:30px;" >C&oacute;digo Objeto:</td>
            <td style="width: 400px;text-align: left;" id="c_codigo"></td>
        </tr>
        <tr>
            <td style="text-align: left;padding-left:30px;">Nombre:</td>
            <td><input id="txt_descripcion" type="text"  class="ui-text" value="" style="width:394px;text-transform: none;" maxlength="250" /></td>
        </tr>
        <tr>
            <td style="text-align: left;padding-left:30px;">Padre:</td>
            <td><select id="cb_padre" style="width:394px;"><?php echo $this->cbPadreHtml ?></select></td>
        </tr>
        <tr>
            <td style="text-align: left;padding-left:30px;" valign="top">Acci&oacute;n:</td>
            <td><textarea rows="1" id="txa_observ" class="ui-text" style="width:394px;text-transform: none;"></textarea></td>
        </tr>

        <tr>
            <td style="text-align: left;padding-left:30px;">Orden:</td>
            <td><input id="txt_long" class="ui-text" type="text" value="" style="width:394px;" /></td>
        </tr>
        <tr>
            <td style="text-align: left;padding-left:30px;">Id Objeto</td>
            <td>
                <input type="text" id="txt_decimal"  class="ui-text" style="width:394px; text-transform: none"  value="">
            </td>
        </tr>
        <tr>
            <td style="text-align: left; padding-left:30px;">Estado:</td>
            <td><select id="cb_estado" class="ui-text" style="width:394px;"> <?php echo $this->cbestadoHtml ?></select></td>
        </tr>
       <!-- <tr>
            <td>Digitos decimales:</td>
            <td><input id="txt_decimal" type="text" value="" style="width:100%" maxlength="250" /></td>
        </tr>
        <tr>
            <td>Valor por Defecto:</td>
            <td><input id="txt_defecto" type="text" value="" style="width:100%" maxlength="250" /></td>
        </tr>--><br>
        <tr>
            <td style="text-align: left;padding-left:30px;padding-top:40px;" valign="top">Nodos Hijos:</td>
            <td>
                <div class="ui-widget ui-widget-content ui-corner-all" style="width: 92%;margin: 3px;">
                    <table style="width: 394px; padding: 2px;" cellspacing="0" border="0" cellpadding="0">
                        <thead class="ui-widget ui-widget-header ui-title2">
                        <tr>
                            <th style="width: 90px">C&oacute;digo</th>
                            <th style="width: 246px">Descripci&oacute;n</th>
                            <th style="width: 42px">Ver</th>
                            <th style="width: 16px">&nbsp;</th>
                        </tr>
                        </thead>
                        <tr>
                            <td colspan="4">
                                <div style="overflow-y:scroll;height: 150px"  id="c_nodohijos">
                                    <table width="372px" border="0" cellspacing="0" cellpadding="0">
                                        <tbody class="ui-table-body">
                                        <tr>
                                            <th style="width: 90px">&nbsp;</th>
                                            <th style="width: 246px">&nbsp;</th>
                                            <th style="width: 42px">&nbsp;</th>
                                            <th style="width: 16px">&nbsp;</th>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
    </table>
<script type="text/javascript">
    themeTextBox();
    themeComboBox();

</script>