<div id="panelbusqueda" align="center" class="ui-widget ui-widget-content ui-corner-all "  style="width: 1200px;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Usuarios</label>
    </div>
    <div id="panelGrid">
    <div id="dvbusqueda">
        <div id="dvaccion"></div>
        <br/>
        <div id="panelResultUsuario">
            <table id="tblResultUsuario"></table>
            <div id="ptblResultUsuario"></div>
        </div>
        <br/>
    </div>

</div>